### PR TITLE
Changes to heatmap and volcano plot to fix #150

### LINKED ISSUE #150: Heatmap node clustering fails under some conditions
While working through PR #149 with @dongbohu, it became clear that the implementation of node clustering has a flaw that is revealed by the database in @dongbohu's development server.

Node clustering fails to run and the JavaScript Console throws the following error:

```
[Error] Error: undefined is not an object (evaluating 'this.activityCache.get(b)[a.node-1].value')
http://165.123.67.202/static/assets/adage-0.7.0b.js:41:1328
map@[native code]
http://165.123.67.202/static/assets/adage-0.7.0b.js:41:1273
map@[native code]
getSignatureObjects@http://165.123.67.202/static/assets/adage-0.7.0b.js:41:1206
http://165.123.67.202/static/assets/adage-0.7.0b.js:41:2835
g@http://165.123.67.202/static/assets/adage-0.7.0b.js:28:9827
http://165.123.67.202/static/assets/adage-0.7.0b.js:28:9999
$digest@http://165.123.67.202/static/assets/adage-0.7.0b.js:28:16130
http://165.123.67.202/static/assets/adage-0.7.0b.js:28:17733
f@http://165.123.67.202/static/assets/adage-0.7.0b.js:26:27932
http://165.123.67.202/static/assets/adage-0.7.0b.js:26:29390
	(anonymous function) (adage-0.7.0b.js:27:20333)
	g (adage-0.7.0b.js:28:9911)
	(anonymous function) (adage-0.7.0b.js:28:10000)
	$digest (adage-0.7.0b.js:28:16131)
	(anonymous function) (adage-0.7.0b.js:28:17734)
	f (adage-0.7.0b.js:26:27933)
	(anonymous function) (adage-0.7.0b.js:26:29391)
```

### PR DESCRIPTION
**Pull request by mhuyck**
This should fix the heatmap issue that @dongbohu and I uncovered last week. Still need to tidy up but filing as a WIP so we can test with Dongbo's database.

### CODE REVIEW

**Comment by mhuyck** [comment]
Hah. There's a conflict because I haven't yet rebased to incorporate @dongbohu's "Node" to "Signature" renaming yet. Will fix that before merging, of course.

**Comment by dongbohu** [comment]
Since `Activity` in model.py has been changed, do I need to rebuild the activity table too?

**Comment by mhuyck** [comment]
I thought I would need to do that, too, but when I ran `makemigrations` it didn't change anything. I suspect that the existing `unique_together` constraint had already made those indexes implicitly.

**Comment by dongbohu** [comment]
The local web server on my desktop is using the latest code, but it doesn't seem to be working:
http://165.123.67.202/#/home
Feel free to play with it.

**Comment by mhuyck** [comment]
I will have a look. Although you won't need to change the database, you will need to update the backend using `sudo supervisorctl restart adage`. Did you do that?

**Comment by dongbohu** [comment]
Yes, I did.

**Comment by mhuyck** [comment]
I don't see the MLModel selector on the page above the heatmap. Are you sure you have the right code?

**Comment by mhuyck** [comment]
Note that you will need to make a fresh clone of the `heatmap-node-order-fix` from *my* repo since we have not yet merged with `greenelab/master`. You cannot just do a `pull` to get your server updated.

**Comment by dongbohu** [comment]
I found the reason: I messed up the new version with another version that was cloned from your repo. Let me fix it.

**Comment by mhuyck** [comment]
Tested this fix with @dongbohu's database and it works. Now tidied up and ready for full review so removing the WIP label.

File: interface/src/app/analyze/analysis/sampleBin.js [hunk 1]
```diff
@@ -161,17 +161,25 @@ MathFuncts, errGen) {
...
             function(sampleId) {
-              // FIXME: counting on array order to match signature order here
-              return this.activityCache.get(sampleId)[val.node - 1].value;
+              var cachedActivity = this.activityCache.get(sampleId);
+              if (cachedActivity[index].node !== val.node) {
+                // ensure we're pulling out the right node (aka signature)
+                $log.error(
+                  'getSignatureObjects: signature IDs do not match. First ' +
+                  ' sample = ', val, ', but sample ' + sampleId + ' =',
+                  cachedActivity[index]
```
Comment (dongbohu) [inline interface/src/app/analyze/analysis/sampleBin.js]: In this error message, both `val` and `cachedActivity[index]` are objects, do you think it makes more sense to only print out `val.node` and `cachedActivity[index].node`?

File: interface/src/app/analyze/analysis/sampleBin.js [hunk 2]
```diff
@@ -432,32 +441,42 @@ MathFuncts, errGen) {
...
+              //      plucking the activity `.value` for each sample within the
+              //      `index`th signature from the `activityCache`
+              //      [inner .map()]
+              var cachedActivity = cbSampleBin.activityCache.get(sampleId);
+              if (cachedActivity[index].node !== signatureId) {
+                // ensure we're pulling out the right node
+                $log.error(
+                  'mapSignaturesToSignatureInfo: signature IDs do not match.' +
+                  ' First sample = ' + signatureId + ', but sample ' +
+                  sampleId + ' =', cachedActivity[index]
```
Comment (dongbohu) [inline interface/src/app/analyze/analysis/sampleBin.js]: Same question on whether to include the unmatched signature ID only in the log.

File: interface/src/app/analyze/analysis/sampleBin.js (hunk 1 above)
Comment (mhuyck) [inline interface/src/app/analyze/analysis/sampleBin.js]: I did that on purpose. It's true that we're just checking the IDs to be sure they match, but if they *don't* match then I think I'll want to see the extra information to help diagnose what is going wrong. I expect this to be a rare error condition, so if it does arise I want it to be easy to track down the source of trouble.

File: interface/src/app/analyze/analysis/sampleBin.js (hunk 2 above)
Comment (mhuyck) [inline interface/src/app/analyze/analysis/sampleBin.js]: This case is slightly less verbose (note that the "first sample," in this case, is including just the `signatureId`. I would have done this the same way as the other error for the same reasons, but we are mapping an array that has already been translated from objects to IDs, so I no longer have the full object.

Anyway, let me know if you still think this is too much to include in the log, given that I expect this will be a rare error condition.

File: interface/src/app/analyze/analysis/sampleBin.js (hunk 1 above)
Comment (dongbohu) [inline interface/src/app/analyze/analysis/sampleBin.js]: Sure. It makes sense.
