### PR TITLE
Node uri post

### LINKED ISSUE #152: Volcano plot fails to load with long Node IDs
Testing some changes on @dongbohu's database revealed a latent bug that will appear when Node IDs grow beyond 3-4 digits. The volcano plot in our test instance failed to load with the following error:

```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (10945;10946;10947;10948;10949;10950;10951;10952;10953;10954;10955;10956;10957;10958;10959;10960;10961;10962;10963;10964;10965;10966;10967;10968;10969;10970;10971;10972;10973;10974;10975;10976;10977;10978;10979;10980;10981;10982;10983;10984;10985;10986;10987;10988;10989;10990;10991;10992;10993;10994;10995;10996;10997;10998;10999;11000;11001;11002;11003;11004;11005;11006;11007;11008;11009;11010;11011;11012;11013;11014;11015;11016;11017;11018;11019;11020;11021;11022;11023;11024;11025;11026;11027;11028;11029;11030;11031;11032;11033;11034;11035;11036;11037;11038;11039;11040;11041;11042;11043;11044;11045;11046;11047;11048;11049;11050;11051;11052;11053;11054;11055;11056;11057;11058;11059;11060;11061;11062;11063;11064;11065;11066;11067;11068;11069;11070;11071;11072;11073;11074;11075;11076;11077;11078;11079;11080;11081;11082;11083;11084;11085;11086;11087;11088;11089;11090;11091;11092;11093;11094;11095;11096;11097;11098;11099;11100;11101;11102;11103;11104;11105;11106;11107;11108;11109;11110;11111;11112;11113;11114;11115;11116;11117;11118;11119;11120;11121;11122;11123;11124;11125;11126;11127;11128;11129;11130;11131;11132;11133;11134;11135;11136;11137;11138;11139;11140;11141;11142;11143;11144;11145;11146;11147;11148;11149;11150;11151;11152;11153;11154;11155;11156;11157;11158;11159;11160;11161;11162;11163;11164;11165;11166;11167;11168;11169;11170;11171;11172;11173;11174;11175;11176;11177;11178;11179;11180;11181;11182;11183;11184;11185;11186;11187;11188;11189;11190;11191;11192;11193;11194;11195;11196;11197;11198;11199;11200;11201;11202;11203;11204;11205;11206;11207;11208;11209;11210;11211;11212;11213;11214;11215;11216;11217;11218;11219;11220;11221;11222;11223;11224;11225;11226;11227;11228;11229;11230;11231;11232;11233;11234;11235;11236;11237;11238;11239;11240;11241;11242;11243;11244;11245;11246;11247;11248;11249;11250;11251;11252;11253;11254;11255;11256;11257;11258;11259;11260;11261;11262;11263;11264;11265;11266;11267;11268;11269;11270;11271;11272;11273;11274;11275;11276;11277;11278;11279;11280;11281;11282;11283;11284;11285;11286;11287;11288;11289;11290;11291;11292;11293;11294;11295;11296;11297;11298;11299;11300;11301;11302;11303;11304;11305;11306;11307;11308;11309;11310;11311;11312;11313;11314;11315;11316;11317;11318;11319;11320;11321;11322;11323;11324;11325;11326;11327;11328;11329;11330;11331;11332;11333;11334;11335;11336;11337;11338;11339;11340;11341;11342;11343;11344;11345;11346;11347;11348;11349;11350;11351;11352;11353;11354;11355;11356;11357;11358;11359;11360;11361;11362;11363;11364;11365;11366;11367;11368;11369;11370;11371;11372;11373;11374;11375;11376;11377;11378;11379;11380;11381;11382;11383;11384;11385;11386;11387;11388;11389;11390;11391;11392;11393;11394;11395;11396;11397;11398;11399;11400;11401;11402;11403;11404;11405;11406;11407;11408;11409;11410;11411;11412;11413;11414;11415;11416;11417;11418;11419;11420;11421;11422;11423;11424;11425;11426;11427;11428;11429;11430;11431;11432;11433;11434;11435;11436;11437;11438;11439;11440;11441;11442;11443;11444;11445;11446;11447;11448;11449;11450;11451;11452;11453;11454;11455;11456;11457;11458;11459;11460;11461;11462;11463;11464;11465;11466;11467;11468;11469;11470;11471;11472;11473;11474;11475;11476;11477;11478;11479;11480;11481;11482;11483;11484;11485;11486;11487;11488;11489;11490;11491;11492;11493;11494;11495;11496;11497;11498;11499;11500;11501;11502;11503;11504;11505;11506;11507;11508;11509;11510;11511;11512;11513;11514;11515;11516;11517;11518;11519;11520;11521;11522;11523;11524;11525;11526;11527;11528;11529;11530;11531;11532;11533;11534;11535;11536;11537;11538;11539;11540;11541;11542;11543;11544, line 0)
[Error] Error retrieving NodeInfoSet: 400 Bad Request
	(anonymous function) (adage-0.6.0b.js:42:17808)
	(anonymous function) (adage-0.6.0b.js:37:12982)
	h (adage-0.6.0b.js:29:12406)
	(anonymous function) (adage-0.6.0b.js:29:12578)
	$digest (adage-0.6.0b.js:29:18538)
	$apply (adage-0.6.0b.js:29:20350)
	i (adage-0.6.0b.js:28:26557)
	u (adage-0.6.0b.js:28:28681)
	onload (adage-0.6.0b.js:28:29154)
[Error] Query errored: 400 Bad Request
	logError (adage-0.6.0b.js:42:18190)
	h (adage-0.6.0b.js:29:12406)
	(anonymous function) (adage-0.6.0b.js:29:12578)
	$digest (adage-0.6.0b.js:29:18538)
	$apply (adage-0.6.0b.js:29:20350)
	i (adage-0.6.0b.js:28:26557)
	u (adage-0.6.0b.js:28:28681)
	onload (adage-0.6.0b.js:28:29154)
```

It appears to be trying to load data from the following API request:
```
http://<hostname>/api/v0/node/set/10945%3B10946%3B10947%3B10948%3B10949%3B10950%3B10951%3B10952%3B10953%3B10954%3B10955%3B10956%3B10957%3B10958%3B10959%3B10960%3B10961%3B10962%3B10963%3B10964%3B10965%3B10966%3B10967%3B10968%3B10969%3B10970%3B10971%3B10972%3B10973%3B10974%3B10975%3B10976%3B10977%3B10978%3B10979%3B10980%3B10981%3B10982%3B10983%3B10984%3B10985%3B10986%3B10987%3B10988%3B10989%3B10990%3B10991%3B10992%3B10993%3B10994%3B10995%3B10996%3B10997%3B10998%3B10999%3B11000%3B11001%3B11002%3B11003%3B11004%3B11005%3B11006%3B11007%3B11008%3B11009%3B11010%3B11011%3B11012%3B11013%3B11014%3B11015%3B11016%3B11017%3B11018%3B11019%3B11020%3B11021%3B11022%3B11023%3B11024%3B11025%3B11026%3B11027%3B11028%3B11029%3B11030%3B11031%3B11032%3B11033%3B11034%3B11035%3B11036%3B11037%3B11038%3B11039%3B11040%3B11041%3B11042%3B11043%3B11044%3B11045%3B11046%3B11047%3B11048%3B11049%3B11050%3B11051%3B11052%3B11053%3B11054%3B11055%3B11056%3B11057%3B11058%3B11059%3B11060%3B11061%3B11062%3B11063%3B11064%3B11065%3B11066%3B11067%3B11068%3B11069%3B11070%3B11071%3B11072%3B11073%3B11074%3B11075%3B11076%3B11077%3B11078%3B11079%3B11080%3B11081%3B11082%3B11083%3B11084%3B11085%3B11086%3B11087%3B11088%3B11089%3B11090%3B11091%3B11092%3B11093%3B11094%3B11095%3B11096%3B11097%3B11098%3B11099%3B11100%3B11101%3B11102%3B11103%3B11104%3B11105%3B11106%3B11107%3B11108%3B11109%3B11110%3B11111%3B11112%3B11113%3B11114%3B11115%3B11116%3B11117%3B11118%3B11119%3B11120%3B11121%3B11122%3B11123%3B11124%3B11125%3B11126%3B11127%3B11128%3B11129%3B11130%3B11131%3B11132%3B11133%3B11134%3B11135%3B11136%3B11137%3B11138%3B11139%3B11140%3B11141%3B11142%3B11143%3B11144%3B11145%3B11146%3B11147%3B11148%3B11149%3B11150%3B11151%3B11152%3B11153%3B11154%3B11155%3B11156%3B11157%3B11158%3B11159%3B11160%3B11161%3B11162%3B11163%3B11164%3B11165%3B11166%3B11167%3B11168%3B11169%3B11170%3B11171%3B11172%3B11173%3B11174%3B11175%3B11176%3B11177%3B11178%3B11179%3B11180%3B11181%3B11182%3B11183%3B11184%3B11185%3B11186%3B11187%3B11188%3B11189%3B11190%3B11191%3B11192%3B11193%3B11194%3B11195%3B11196%3B11197%3B11198%3B11199%3B11200%3B11201%3B11202%3B11203%3B11204%3B11205%3B11206%3B11207%3B11208%3B11209%3B11210%3B11211%3B11212%3B11213%3B11214%3B11215%3B11216%3B11217%3B11218%3B11219%3B11220%3B11221%3B11222%3B11223%3B11224%3B11225%3B11226%3B11227%3B11228%3B11229%3B11230%3B11231%3B11232%3B11233%3B11234%3B11235%3B11236%3B11237%3B11238%3B11239%3B11240%3B11241%3B11242%3B11243%3B11244%3B11245%3B11246%3B11247%3B11248%3B11249%3B11250%3B11251%3B11252%3B11253%3B11254%3B11255%3B11256%3B11257%3B11258%3B11259%3B11260%3B11261%3B11262%3B11263%3B11264%3B11265%3B11266%3B11267%3B11268%3B11269%3B11270%3B11271%3B11272%3B11273%3B11274%3B11275%3B11276%3B11277%3B11278%3B11279%3B11280%3B11281%3B11282%3B11283%3B11284%3B11285%3B11286%3B11287%3B11288%3B11289%3B11290%3B11291%3B11292%3B11293%3B11294%3B11295%3B11296%3B11297%3B11298%3B11299%3B11300%3B11301%3B11302%3B11303%3B11304%3B11305%3B11306%3B11307%3B11308%3B11309%3B11310%3B11311%3B11312%3B11313%3B11314%3B11315%3B11316%3B11317%3B11318%3B11319%3B11320%3B11321%3B11322%3B11323%3B11324%3B11325%3B11326%3B11327%3B11328%3B11329%3B11330%3B11331%3B11332%3B11333%3B11334%3B11335%3B11336%3B11337%3B11338%3B11339%3B11340%3B11341%3B11342%3B11343%3B11344%3B11345%3B11346%3B11347%3B11348%3B11349%3B11350%3B11351%3B11352%3B11353%3B11354%3B11355%3B11356%3B11357%3B11358%3B11359%3B11360%3B11361%3B11362%3B11363%3B11364%3B11365%3B11366%3B11367%3B11368%3B11369%3B11370%3B11371%3B11372%3B11373%3B11374%3B11375%3B11376%3B11377%3B11378%3B11379%3B11380%3B11381%3B11382%3B11383%3B11384%3B11385%3B11386%3B11387%3B11388%3B11389%3B11390%3B11391%3B11392%3B11393%3B11394%3B11395%3B11396%3B11397%3B11398%3B11399%3B11400%3B11401%3B11402%3B11403%3B11404%3B11405%3B11406%3B11407%3B11408%3B11409%3B11410%3B11411%3B11412%3B11413%3B11414%3B11415%3B11416%3B11417%3B11418%3B11419%3B11420%3B11421%3B11422%3B11423%3B11424%3B11425%3B11426%3B11427%3B11428%3B11429%3B11430%3B11431%3B11432%3B11433%3B11434%3B11435%3B11436%3B11437%3B11438%3B11439%3B11440%3B11441%3B11442%3B11443%3B11444%3B11445%3B11446%3B11447%3B11448%3B11449%3B11450%3B11451%3B11452%3B11453%3B11454%3B11455%3B11456%3B11457%3B11458%3B11459%3B11460%3B11461%3B11462%3B11463%3B11464%3B11465%3B11466%3B11467%3B11468%3B11469%3B11470%3B11471%3B11472%3B11473%3B11474%3B11475%3B11476%3B11477%3B11478%3B11479%3B11480%3B11481%3B11482%3B11483%3B11484%3B11485%3B11486%3B11487%3B11488%3B11489%3B11490%3B11491%3B11492%3B11493%3B11494%3B11495%3B11496%3B11497%3B11498%3B11499%3B11500%3B11501%3B11502%3B11503%3B11504%3B11505%3B11506%3B11507%3B11508%3B11509%3B11510%3B11511%3B11512%3B11513%3B11514%3B11515%3B11516%3B11517%3B11518%3B11519%3B11520%3B11521%3B11522%3B11523%3B11524%3B11525%3B11526%3B11527%3B11528%3B11529%3B11530%3B11531%3B11532%3B11533%3B11534%3B11535%3B11536%3B11537%3B11538%3B11539%3B11540%3B11541%3B11542%3B11543%3B11544/
```

### PR DESCRIPTION
**Pull request by mhuyck**
This set of changes fixes #152.

### CODE REVIEW

File: interface/src/app/analyze/analysis/sampleBin.js [hunk 1]
```diff
@@ -14,7 +14,16 @@ angular.module('adage.analyze.sampleBin', [
 
 .factory('SignatureSet', ['$resource', 'ApiBasePath',
```
Comment (dongbohu) [inline interface/src/app/analyze/analysis/sampleBin.js]: @mhuyck: I have been wondering whether it is a good idea to move all signature-related resource classes to `signature/resources.js` file but haven't found time to do it yet. Since you are working on this service, what do you think?

After this service is moved to `signature/resources.js`, you can also remove the `ngResource` dependency on line 8.

Comment (mhuyck) [inline interface/src/app/analyze/analysis/sampleBin.js]: That is a good idea, but out of scope for this PR. I'd like to keep this focused on issue #152.

**Comment by mhuyck** [comment]
Test case is a good idea. I will follow the pattern I used for the last bug like this.

File: adage/analyze/api.py [hunk 2]
```diff
@@ -275,12 +275,37 @@ class Meta:
         queryset = Node.objects.all()
         resource_name = 'node'
         allowed_methods = ['get']
+        multiple_allowed_methods = ['post']
```
Comment (rzelayafavila) [inline adage/analyze/api.py]: Hmmm, I haven't been able to find any docs on this Meta ``multiple_allowed_methods`` attribute. Is it a custom one you made for this functionality?

File: adage/analyze/api.py [hunk 3]
```diff
@@ -275,12 +275,37 @@ class Meta:
...
+                 r'post_multiple%s$') %
+                (self._meta.resource_name, trailing_slash()),
+                self.wrap_view('dispatch_multiple'),
+                name='api_post_multiple'),
+        ]
+
+    def dispatch_multiple(self, request, **kwargs):
+        return self.dispatch('multiple', request, **kwargs)
+
+    def post_multiple(self, request, **kwargs):
```
Comment (rzelayafavila) [inline adage/analyze/api.py]: So tastypie will automatically call this method when someone posts to the ``.../post_multiple`` url? Does it get called somehow behind the scenes when ``dispatch_multiple()`` gets called?

File: interface/src/app/analyze/analysis/sampleBin.js [hunk 4]
```diff
@@ -14,7 +14,16 @@ angular.module('adage.analyze.sampleBin', [
...
   function($resource, ApiBasePath) {
-    return $resource(ApiBasePath + 'node/set/:ids/');
+    return $resource(
+      ApiBasePath + 'node/post_multiple/',
+      {},
+      {post: {
+        method: 'POST',
+        // Setting Content-Type is required. Django will not process the
+        // POST data the way Angular's defaults send it.
+        headers: {'Content-Type': 'application/x-www-form-urlencoded'}
```
Comment (rzelayafavila) [inline interface/src/app/analyze/analysis/sampleBin.js]: :+1:

File: adage/analyze/api.py (hunk 2 above)
Comment (mhuyck) [inline adage/analyze/api.py]: Yes. This follows the technique we developed a while back for taking advantage of the built-in Tastypie `dispatch` functionality.

File: adage/analyze/api.py (hunk 3 above)
Comment (mhuyck) [inline adage/analyze/api.py]: Bingo. The Python method name to call is built from the HTTP request method (POST, in this case) combined with the dispatch "target".

File: interface/src/app/analyze/analysis/sampleBin.js (hunk 4 above)
Comment (mhuyck) [inline interface/src/app/analyze/analysis/sampleBin.js]: This was required last time around, but in this case it's not actually encoded as form data or as JSON data. Although it works this way, it's not actually quite right. I'm about to push an update that makes it `'text/plain'` to clarify.

Comment (mhuyck) [inline interface/src/app/analyze/analysis/sampleBin.js]: Actually... hmm. Maybe the simplest fix for the testing problem I hit would be to keep this `Content-Type` as form-urlencoded and actually encode the POST body that way. Let me try that.

Comment (mhuyck) [inline interface/src/app/analyze/analysis/sampleBin.js]: It was a good idea, but didn't work out. I've reverted the implementation to this `'text/plain'` encoding. Filing an issue to sort out the testing glitch that this causes as a separate PR.

**Comment by mhuyck** [comment]
I have to defer the implementation of the test for this. If I use an encoding of `text/plain`, it trips up the serializer in Tastypie's `api_client.post()` (which I really want to do NOTHING). If I revert to `application/x-www-form-urlencoded` then I have trouble with getting the post body where it needs to land for some reason I haven't totally worked out.

The way this API works is just a little too different from the last fix I implemented for enabling POST to be handled as a GET.

**Comment by mhuyck** [comment]
I think I have now responded to all feedback on this PR other than the request for the test. Please let me know if you think it's okay to merge.
